name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run github
          record: true
        env:
          # for recording test results and videos to Cypress Dashboard
          CYPRESS_RECORD_KEY: 2559c50c-2abd-4d88-a46f-b7c55514972e